# Generated by Django 4.0.4 on 2022-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='postImage'),
        ),
    ]
